name: jcvi
channels:
  - conda-forge
  - bioconda
dependencies:
  - python 3.12
  - bedtools
  - imagemagick
  - libmagic # System-level magic library
  - wand # Python bindings for ImageMagick
  - pip
  - pip:
      - black
      - hatch
      - mock
      - pytest
      - pytest-benchmark
      - pytest-cov
      - PyYAML
